name: deploy.yml
on:
  push:
    branches:
      - main # Otomatis deploy setiap ada push/merge ke branch main

jobs:
  web-deploy:
    name: Fast Deploy to DirectAdmin
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Sync files to DirectAdmin (Source Code Only)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/homebase.tsu.ac.id/public_html/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            README.md
            *.sqlite
            phpunit.xml
            sources/vendor/**
            sources/resources/css/**
            sources/resources/js/**
            sources/vite.config.js
            sources/tailwind.config.js
            sources/postcss.config.js
            sources/package.json
            sources/package-lock.json
            node_modules/**
            .idea/**
            .vscode/**
            .DS_Store
            sources/storage/logs/*.log

      - name: Execute Server Scripts via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          # Kamu perlu nambahin secret SSH ini di repo GitHub kamu
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd domains/homebase.tsu.ac.id/public_html/sources
            mkdir -p storage/framework/{sessions,views,cache}
            mkdir -p bootstrap/cache
            chmod -R 775 storage bootstrap/cache
            /usr/local/bin/composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache