name: Tests

on:
  push:
    branches:
      - main
      - development
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.4]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Create Framework Directories
        run: |
          cd sources
          mkdir -p storage/framework/{sessions,views,cache}
          mkdir -p bootstrap/cache
          chmod -R 775 storage bootstrap/cache
          mkdir -p database
          touch database/database.sqlite

      - name: Install Composer dependencies
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          cd sources
          composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: |
          cd sources
          cp .env.example .env

      - name: Generate app key
        run: |
          cd sources
          php artisan key:generate

      - name: Execute tests
        run: |
          cd sources
          php artisan test